# Generated by Django 3.2.15 on 2022-08-25 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='households', to='payment.Program'),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_infos', to='household.individual'),
        ),
    ]
